# Generated by Django 5.1.5 on 2025-01-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_engineer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='contact_mode',
        ),
    ]
