# Generated by Django 5.1.5 on 2025-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_contact_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolution_steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
