# Generated by Django 5.0 on 2025-01-29 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_ticket_id_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
